language: python
python:
 - 2.7
services:
 - docker
install:
 - docker build . -t mrjin/google-proxy:$tag
 - docker run -d -p 80:80 --name proxy mrjin/shadowsocks:$tag
script:
 - docker ps
 - curl http://127.0.0.1
 - docker login -u $user -p $password
 - docker push mrjin/shadowsocks:$tag